
USE CLARITY;
:OUT \\Client\F$\clarity\note-2014-01-01.rpt
SET NOCOUNT ON
SELECT DISTINCT csn.EXTERNAL_ID CSN_ID
  ,info.NOTE_ID
  ,prov_type.NAME AuthorType
  ,TYPINDEX.NAME NoteType
  ,info.CREATE_INSTANT_DTTM
  ,txt.line
  ,TXT.NOTE_TEXT
  ,txt.CONTACT_DATE_REAL
  ,noteStat.NAME NoteStatus
  ,noteEncs.SPEC_NOTE_TIME_DTTM
  ,noteEncs.ENTRY_INSTANT_DTTM
FROM Analytics.dbo.CCDA643_CSNLookupTable csn
INNER JOIN dbo.HNO_INFO info ON info.PAT_ENC_CSN_ID = csn.PAT_ENC_CSN_ID
INNER JOIN dbo.note_enc_info noteEncs ON noteEncs.NOTE_ID = info.NOTE_ID
INNER JOIN dbo.HNO_NOTE_TEXT txt ON txt.NOTE_CSN_ID = noteEncs.CONTACT_SERIAL_NUM
INNER JOIN dbo.ZC_NOTE_TYPE_IP TYPINDEX ON info.IP_NOTE_TYPE_C = TYPINDEX.TYPE_IP_C
INNER JOIN dbo.CLARITY_EMP emp ON emp."USER_ID" = noteEncs.AUTHOR_USER_ID
INNER JOIN dbo.CLARITY_SER ser ON ser.PROV_ID = emp.PROV_ID
INNER JOIN dbo.ZC_PROV_TYPE PROV_TYPE ON PROV_TYPE.PROV_TYPE_C = ser.PROVIDER_TYPE_C
LEFT JOIN dbo.ZC_NOTE_STATUS noteStat ON noteStat.NOTE_STATUS_C = noteEncs.NOTE_STATUS_C
WHERE info.DELETE_USER_ID IS NULL
  AND (
    info.UNSIGNED_YN IS NULL
    OR info.unsigned_yn = 'N'
    )
  AND (
    info.AMB_NOTE_YN IS NULL
    OR info.AMB_NOTE_YN = 'N'
    )
    and (noteEncs.NOTE_STATUS_C NOT IN (1,4,8) OR noteEncs.NOTE_STATUS_C IS NULL)
    AND info.CREATE_INSTANT_DTTM >= '2014-01-01'
    AND info.CREATE_INSTANT_DTTM < '2014-07-01';
GO


USE CLARITY;
:OUT \\Client\F$\clarity\note-2014-07-01.rpt
SET NOCOUNT ON
SELECT DISTINCT csn.EXTERNAL_ID CSN_ID
  ,info.NOTE_ID
  ,prov_type.NAME AuthorType
  ,TYPINDEX.NAME NoteType
  ,info.CREATE_INSTANT_DTTM
  ,txt.line
  ,TXT.NOTE_TEXT
  ,txt.CONTACT_DATE_REAL
  ,noteStat.NAME NoteStatus
  ,noteEncs.SPEC_NOTE_TIME_DTTM
  ,noteEncs.ENTRY_INSTANT_DTTM
FROM Analytics.dbo.CCDA643_CSNLookupTable csn
INNER JOIN dbo.HNO_INFO info ON info.PAT_ENC_CSN_ID = csn.PAT_ENC_CSN_ID
INNER JOIN dbo.note_enc_info noteEncs ON noteEncs.NOTE_ID = info.NOTE_ID
INNER JOIN dbo.HNO_NOTE_TEXT txt ON txt.NOTE_CSN_ID = noteEncs.CONTACT_SERIAL_NUM
INNER JOIN dbo.ZC_NOTE_TYPE_IP TYPINDEX ON info.IP_NOTE_TYPE_C = TYPINDEX.TYPE_IP_C
INNER JOIN dbo.CLARITY_EMP emp ON emp."USER_ID" = noteEncs.AUTHOR_USER_ID
INNER JOIN dbo.CLARITY_SER ser ON ser.PROV_ID = emp.PROV_ID
INNER JOIN dbo.ZC_PROV_TYPE PROV_TYPE ON PROV_TYPE.PROV_TYPE_C = ser.PROVIDER_TYPE_C
LEFT JOIN dbo.ZC_NOTE_STATUS noteStat ON noteStat.NOTE_STATUS_C = noteEncs.NOTE_STATUS_C
WHERE info.DELETE_USER_ID IS NULL
  AND (
    info.UNSIGNED_YN IS NULL
    OR info.unsigned_yn = 'N'
    )
  AND (
    info.AMB_NOTE_YN IS NULL
    OR info.AMB_NOTE_YN = 'N'
    )
    and (noteEncs.NOTE_STATUS_C NOT IN (1,4,8) OR noteEncs.NOTE_STATUS_C IS NULL)
    AND info.CREATE_INSTANT_DTTM >= '2014-07-01'
    AND info.CREATE_INSTANT_DTTM < '2015-01-01';
GO


USE CLARITY;
:OUT \\Client\F$\clarity\note-2015-01-01.rpt
SET NOCOUNT ON
SELECT DISTINCT csn.EXTERNAL_ID CSN_ID
  ,info.NOTE_ID
  ,prov_type.NAME AuthorType
  ,TYPINDEX.NAME NoteType
  ,info.CREATE_INSTANT_DTTM
  ,txt.line
  ,TXT.NOTE_TEXT
  ,txt.CONTACT_DATE_REAL
  ,noteStat.NAME NoteStatus
  ,noteEncs.SPEC_NOTE_TIME_DTTM
  ,noteEncs.ENTRY_INSTANT_DTTM
FROM Analytics.dbo.CCDA643_CSNLookupTable csn
INNER JOIN dbo.HNO_INFO info ON info.PAT_ENC_CSN_ID = csn.PAT_ENC_CSN_ID
INNER JOIN dbo.note_enc_info noteEncs ON noteEncs.NOTE_ID = info.NOTE_ID
INNER JOIN dbo.HNO_NOTE_TEXT txt ON txt.NOTE_CSN_ID = noteEncs.CONTACT_SERIAL_NUM
INNER JOIN dbo.ZC_NOTE_TYPE_IP TYPINDEX ON info.IP_NOTE_TYPE_C = TYPINDEX.TYPE_IP_C
INNER JOIN dbo.CLARITY_EMP emp ON emp."USER_ID" = noteEncs.AUTHOR_USER_ID
INNER JOIN dbo.CLARITY_SER ser ON ser.PROV_ID = emp.PROV_ID
INNER JOIN dbo.ZC_PROV_TYPE PROV_TYPE ON PROV_TYPE.PROV_TYPE_C = ser.PROVIDER_TYPE_C
LEFT JOIN dbo.ZC_NOTE_STATUS noteStat ON noteStat.NOTE_STATUS_C = noteEncs.NOTE_STATUS_C
WHERE info.DELETE_USER_ID IS NULL
  AND (
    info.UNSIGNED_YN IS NULL
    OR info.unsigned_yn = 'N'
    )
  AND (
    info.AMB_NOTE_YN IS NULL
    OR info.AMB_NOTE_YN = 'N'
    )
    and (noteEncs.NOTE_STATUS_C NOT IN (1,4,8) OR noteEncs.NOTE_STATUS_C IS NULL)
    AND info.CREATE_INSTANT_DTTM >= '2015-01-01'
    AND info.CREATE_INSTANT_DTTM < '2015-07-01';
GO


USE CLARITY;
:OUT \\Client\F$\clarity\note-2015-07-01.rpt
SET NOCOUNT ON
SELECT DISTINCT csn.EXTERNAL_ID CSN_ID
  ,info.NOTE_ID
  ,prov_type.NAME AuthorType
  ,TYPINDEX.NAME NoteType
  ,info.CREATE_INSTANT_DTTM
  ,txt.line
  ,TXT.NOTE_TEXT
  ,txt.CONTACT_DATE_REAL
  ,noteStat.NAME NoteStatus
  ,noteEncs.SPEC_NOTE_TIME_DTTM
  ,noteEncs.ENTRY_INSTANT_DTTM
FROM Analytics.dbo.CCDA643_CSNLookupTable csn
INNER JOIN dbo.HNO_INFO info ON info.PAT_ENC_CSN_ID = csn.PAT_ENC_CSN_ID
INNER JOIN dbo.note_enc_info noteEncs ON noteEncs.NOTE_ID = info.NOTE_ID
INNER JOIN dbo.HNO_NOTE_TEXT txt ON txt.NOTE_CSN_ID = noteEncs.CONTACT_SERIAL_NUM
INNER JOIN dbo.ZC_NOTE_TYPE_IP TYPINDEX ON info.IP_NOTE_TYPE_C = TYPINDEX.TYPE_IP_C
INNER JOIN dbo.CLARITY_EMP emp ON emp."USER_ID" = noteEncs.AUTHOR_USER_ID
INNER JOIN dbo.CLARITY_SER ser ON ser.PROV_ID = emp.PROV_ID
INNER JOIN dbo.ZC_PROV_TYPE PROV_TYPE ON PROV_TYPE.PROV_TYPE_C = ser.PROVIDER_TYPE_C
LEFT JOIN dbo.ZC_NOTE_STATUS noteStat ON noteStat.NOTE_STATUS_C = noteEncs.NOTE_STATUS_C
WHERE info.DELETE_USER_ID IS NULL
  AND (
    info.UNSIGNED_YN IS NULL
    OR info.unsigned_yn = 'N'
    )
  AND (
    info.AMB_NOTE_YN IS NULL
    OR info.AMB_NOTE_YN = 'N'
    )
    and (noteEncs.NOTE_STATUS_C NOT IN (1,4,8) OR noteEncs.NOTE_STATUS_C IS NULL)
    AND info.CREATE_INSTANT_DTTM >= '2015-07-01'
    AND info.CREATE_INSTANT_DTTM < '2016-01-01';
GO


USE CLARITY;
:OUT \\Client\F$\clarity\note-2016-01-01.rpt
SET NOCOUNT ON
SELECT DISTINCT csn.EXTERNAL_ID CSN_ID
  ,info.NOTE_ID
  ,prov_type.NAME AuthorType
  ,TYPINDEX.NAME NoteType
  ,info.CREATE_INSTANT_DTTM
  ,txt.line
  ,TXT.NOTE_TEXT
  ,txt.CONTACT_DATE_REAL
  ,noteStat.NAME NoteStatus
  ,noteEncs.SPEC_NOTE_TIME_DTTM
  ,noteEncs.ENTRY_INSTANT_DTTM
FROM Analytics.dbo.CCDA643_CSNLookupTable csn
INNER JOIN dbo.HNO_INFO info ON info.PAT_ENC_CSN_ID = csn.PAT_ENC_CSN_ID
INNER JOIN dbo.note_enc_info noteEncs ON noteEncs.NOTE_ID = info.NOTE_ID
INNER JOIN dbo.HNO_NOTE_TEXT txt ON txt.NOTE_CSN_ID = noteEncs.CONTACT_SERIAL_NUM
INNER JOIN dbo.ZC_NOTE_TYPE_IP TYPINDEX ON info.IP_NOTE_TYPE_C = TYPINDEX.TYPE_IP_C
INNER JOIN dbo.CLARITY_EMP emp ON emp."USER_ID" = noteEncs.AUTHOR_USER_ID
INNER JOIN dbo.CLARITY_SER ser ON ser.PROV_ID = emp.PROV_ID
INNER JOIN dbo.ZC_PROV_TYPE PROV_TYPE ON PROV_TYPE.PROV_TYPE_C = ser.PROVIDER_TYPE_C
LEFT JOIN dbo.ZC_NOTE_STATUS noteStat ON noteStat.NOTE_STATUS_C = noteEncs.NOTE_STATUS_C
WHERE info.DELETE_USER_ID IS NULL
  AND (
    info.UNSIGNED_YN IS NULL
    OR info.unsigned_yn = 'N'
    )
  AND (
    info.AMB_NOTE_YN IS NULL
    OR info.AMB_NOTE_YN = 'N'
    )
    and (noteEncs.NOTE_STATUS_C NOT IN (1,4,8) OR noteEncs.NOTE_STATUS_C IS NULL)
    AND info.CREATE_INSTANT_DTTM >= '2016-01-01'
    AND info.CREATE_INSTANT_DTTM < '2016-07-01';
GO


USE CLARITY;
:OUT \\Client\F$\clarity\note-2016-07-01.rpt
SET NOCOUNT ON
SELECT DISTINCT csn.EXTERNAL_ID CSN_ID
  ,info.NOTE_ID
  ,prov_type.NAME AuthorType
  ,TYPINDEX.NAME NoteType
  ,info.CREATE_INSTANT_DTTM
  ,txt.line
  ,TXT.NOTE_TEXT
  ,txt.CONTACT_DATE_REAL
  ,noteStat.NAME NoteStatus
  ,noteEncs.SPEC_NOTE_TIME_DTTM
  ,noteEncs.ENTRY_INSTANT_DTTM
FROM Analytics.dbo.CCDA643_CSNLookupTable csn
INNER JOIN dbo.HNO_INFO info ON info.PAT_ENC_CSN_ID = csn.PAT_ENC_CSN_ID
INNER JOIN dbo.note_enc_info noteEncs ON noteEncs.NOTE_ID = info.NOTE_ID
INNER JOIN dbo.HNO_NOTE_TEXT txt ON txt.NOTE_CSN_ID = noteEncs.CONTACT_SERIAL_NUM
INNER JOIN dbo.ZC_NOTE_TYPE_IP TYPINDEX ON info.IP_NOTE_TYPE_C = TYPINDEX.TYPE_IP_C
INNER JOIN dbo.CLARITY_EMP emp ON emp."USER_ID" = noteEncs.AUTHOR_USER_ID
INNER JOIN dbo.CLARITY_SER ser ON ser.PROV_ID = emp.PROV_ID
INNER JOIN dbo.ZC_PROV_TYPE PROV_TYPE ON PROV_TYPE.PROV_TYPE_C = ser.PROVIDER_TYPE_C
LEFT JOIN dbo.ZC_NOTE_STATUS noteStat ON noteStat.NOTE_STATUS_C = noteEncs.NOTE_STATUS_C
WHERE info.DELETE_USER_ID IS NULL
  AND (
    info.UNSIGNED_YN IS NULL
    OR info.unsigned_yn = 'N'
    )
  AND (
    info.AMB_NOTE_YN IS NULL
    OR info.AMB_NOTE_YN = 'N'
    )
    and (noteEncs.NOTE_STATUS_C NOT IN (1,4,8) OR noteEncs.NOTE_STATUS_C IS NULL)
    AND info.CREATE_INSTANT_DTTM >= '2016-07-01'
    AND info.CREATE_INSTANT_DTTM < '2017-01-01';
GO


USE CLARITY;
:OUT \\Client\F$\clarity\note-2017-01-01.rpt
SET NOCOUNT ON
SELECT DISTINCT csn.EXTERNAL_ID CSN_ID
  ,info.NOTE_ID
  ,prov_type.NAME AuthorType
  ,TYPINDEX.NAME NoteType
  ,info.CREATE_INSTANT_DTTM
  ,txt.line
  ,TXT.NOTE_TEXT
  ,txt.CONTACT_DATE_REAL
  ,noteStat.NAME NoteStatus
  ,noteEncs.SPEC_NOTE_TIME_DTTM
  ,noteEncs.ENTRY_INSTANT_DTTM
FROM Analytics.dbo.CCDA643_CSNLookupTable csn
INNER JOIN dbo.HNO_INFO info ON info.PAT_ENC_CSN_ID = csn.PAT_ENC_CSN_ID
INNER JOIN dbo.note_enc_info noteEncs ON noteEncs.NOTE_ID = info.NOTE_ID
INNER JOIN dbo.HNO_NOTE_TEXT txt ON txt.NOTE_CSN_ID = noteEncs.CONTACT_SERIAL_NUM
INNER JOIN dbo.ZC_NOTE_TYPE_IP TYPINDEX ON info.IP_NOTE_TYPE_C = TYPINDEX.TYPE_IP_C
INNER JOIN dbo.CLARITY_EMP emp ON emp."USER_ID" = noteEncs.AUTHOR_USER_ID
INNER JOIN dbo.CLARITY_SER ser ON ser.PROV_ID = emp.PROV_ID
INNER JOIN dbo.ZC_PROV_TYPE PROV_TYPE ON PROV_TYPE.PROV_TYPE_C = ser.PROVIDER_TYPE_C
LEFT JOIN dbo.ZC_NOTE_STATUS noteStat ON noteStat.NOTE_STATUS_C = noteEncs.NOTE_STATUS_C
WHERE info.DELETE_USER_ID IS NULL
  AND (
    info.UNSIGNED_YN IS NULL
    OR info.unsigned_yn = 'N'
    )
  AND (
    info.AMB_NOTE_YN IS NULL
    OR info.AMB_NOTE_YN = 'N'
    )
    and (noteEncs.NOTE_STATUS_C NOT IN (1,4,8) OR noteEncs.NOTE_STATUS_C IS NULL)
    AND info.CREATE_INSTANT_DTTM >= '2017-01-01'
    AND info.CREATE_INSTANT_DTTM < '2017-07-01';
GO


USE CLARITY;
:OUT \\Client\F$\clarity\note-2017-07-01.rpt
SET NOCOUNT ON
SELECT DISTINCT csn.EXTERNAL_ID CSN_ID
  ,info.NOTE_ID
  ,prov_type.NAME AuthorType
  ,TYPINDEX.NAME NoteType
  ,info.CREATE_INSTANT_DTTM
  ,txt.line
  ,TXT.NOTE_TEXT
  ,txt.CONTACT_DATE_REAL
  ,noteStat.NAME NoteStatus
  ,noteEncs.SPEC_NOTE_TIME_DTTM
  ,noteEncs.ENTRY_INSTANT_DTTM
FROM Analytics.dbo.CCDA643_CSNLookupTable csn
INNER JOIN dbo.HNO_INFO info ON info.PAT_ENC_CSN_ID = csn.PAT_ENC_CSN_ID
INNER JOIN dbo.note_enc_info noteEncs ON noteEncs.NOTE_ID = info.NOTE_ID
INNER JOIN dbo.HNO_NOTE_TEXT txt ON txt.NOTE_CSN_ID = noteEncs.CONTACT_SERIAL_NUM
INNER JOIN dbo.ZC_NOTE_TYPE_IP TYPINDEX ON info.IP_NOTE_TYPE_C = TYPINDEX.TYPE_IP_C
INNER JOIN dbo.CLARITY_EMP emp ON emp."USER_ID" = noteEncs.AUTHOR_USER_ID
INNER JOIN dbo.CLARITY_SER ser ON ser.PROV_ID = emp.PROV_ID
INNER JOIN dbo.ZC_PROV_TYPE PROV_TYPE ON PROV_TYPE.PROV_TYPE_C = ser.PROVIDER_TYPE_C
LEFT JOIN dbo.ZC_NOTE_STATUS noteStat ON noteStat.NOTE_STATUS_C = noteEncs.NOTE_STATUS_C
WHERE info.DELETE_USER_ID IS NULL
  AND (
    info.UNSIGNED_YN IS NULL
    OR info.unsigned_yn = 'N'
    )
  AND (
    info.AMB_NOTE_YN IS NULL
    OR info.AMB_NOTE_YN = 'N'
    )
    and (noteEncs.NOTE_STATUS_C NOT IN (1,4,8) OR noteEncs.NOTE_STATUS_C IS NULL)
    AND info.CREATE_INSTANT_DTTM >= '2017-07-01'
    AND info.CREATE_INSTANT_DTTM < '2018-01-01';
GO

