select * from
(SELECT
  IP_FLO_GP_DATA.FLO_MEAS_NAME
  ,IP_FLO_GP_DATA.DISP_NAME
  ,IP_FLWSHT_MEAS.FLO_MEAS_ID
  ,rowtype.NAME ROW_TYPE
  ,intakeType.NAME INTAKE_TYPE
  ,outputType.NAME OUTPUT_TYPE
  ,IP_FLWSHT_MEAS.RECORDED_TIME TimeTaken
  ,CASE
    WHEN IP_FLO_GP_DATA.val_type_c = 5
      THEN convert(FLOAT, IP_FLWSHT_MEAS.MEAS_VALUE) / 16.0
    ELSE NULL
    END ConvertedWeightValue
  ,meas_value Value
  ,IP_FLO_GP_DATA.UNITS
  ,flt.TEMPLATE_ID
  ,flt.TEMPLATE_NAME
  ,flt.DISPLAY_NAME TEMPLATE_DISP_NAME
  , row_number() over (Partition By IP_FLWSHT_MEAS.FLO_MEAS_ID
  order by IP_FLWSHT_MEAS.RECORDED_TIME desc) as rn
FROM CLARITY.dbo.IP_FLWSHT_MEAS IP_FLWSHT_MEAS
INNER JOIN CLARITY.dbo.IP_FLO_GP_DATA IP_FLO_GP_DATA ON IP_FLWSHT_MEAS.FLO_MEAS_ID = IP_FLO_GP_DATA.FLO_MEAS_ID
INNER JOIN CLARITY.dbo.IP_FLWSHT_REC IP_FLWSHT_REC ON IP_FLWSHT_MEAS.FSD_ID = IP_FLWSHT_REC.FSD_ID
LEFT JOIN CLARITY.DBO.IP_FLOWSHEET_ROWS RWS ON RWS.LINE = IP_FLWSHT_MEAS.OCCURANCE
  AND IP_FLWSHT_MEAS.FSD_ID = RWS.INPATIENT_DATA_ID
LEFT JOIN CLARITY.dbo.IP_FLT_DATA flt ON flt.TEMPLATE_ID = IP_FLWSHT_MEAS.FLT_ID
LEFT JOIN CLARITY.DBO.ZC_ROW_TYP rowtype ON rowtype.ROW_TYP_C = ip_flo_gp_data.ROW_TYP_C
LEFT JOIN CLARITY.DBO.ZC_INTAKE_TYPE_P intakeType ON intakeType.INTAKE_TYPe_P_C = ip_flo_gp_data.INTAKE_TYP_C
LEFT JOIN CLARITY.DBO.ZC_OUTPUT_TYPE_P outputType ON outputType.OUTPUT_TYPE_P_C = ip_flo_gp_data.OUTPUT_TYP_C
WHERE
IP_FLWSHT_MEAS.RECORDED_TIME >= DATEADD(day,-30, GETDATE())
and
  IP_FLWSHT_MEAS.FLO_MEAS_ID in
(
'1',
'2',
'5',
'6',
'8',
'9',
'10',
'11',
'12',
'13',
'14',
'20',
'41',
'42',
'50',
'51',
'53',
'60',
'103',
'104',
'105',
'111',
'115',
'116',
'1002',
'1036',
'1037',
'1039',
'1040',
'1063',
'1065',
'1086',
'1087',
'1088',
'10097',
'10105',
'10106',
'10130',
'10360',
'10362',
'10649',
'10653',
'10710',
'10776',
'10778',
'10845',
'10849',
'11017',
'34300',
'1074214220')
) rs where rn <= 100