autoscalingGroups:
  - name: web.cluster-prod.jh.opsdx.io
    minSize: 2
    maxSize: 10
  - name: etl.cluster-prod.jh.opsdx.io
    minSize: 1
    maxSize: 10
  - name: nodes.cluster-prod.jh.opsdx.io
    minSize: 2
    maxSize: 10
  - name: spot-nodes.cluster-prod.jh.opsdx.io
    minSize: 2
    maxSize: 10
nodeSelector:
  opsdx_nodegroup: nodes
replicaCount: 2
resources:
  limits:
    cpu: 100m
    memory: 300Mi
  requests:
    cpu: 100m
    memory: 300Mi
extraArgs:
  skip-nodes-with-system-pods: false
  stderrthreshold: info
  v: 4
