SELECT DISTINCT pat.EXTERNAL_ID PAT_ID
	,CSN.EXTERNAL_ID CSN_ID
	,CAST(COALESCE(Encounter.DEPARTMENT_ID, HospitalEncounter.DEPARTMENT_ID) AS VARCHAR(50)) DEPARTMENTID
	,COALESCE(ProblemList.NOTED_DATE, FirstHistory.HX_DATE_OF_ENTRY) FirstDocumented
	,CASE ProblemList.PROBLEM_STATUS_C
		WHEN 2
			THEN ProblemList.RESOLVED_DATE
		END ResolvedDate
	,CAST(CASE 
			WHEN ProblemList.PROBLEM_STATUS_C IS NULL
				THEN 'Active'
			WHEN StatusCategory.PROBLEM_STATUS_C IS NULL
				THEN '*Unknown'
			ELSE StatusCategory.NAME
			END AS VARCHAR(300)) ProblemSTATUS
	,CAST(CASE 
			WHEN ProblemList.HOSPITAL_PL_YN = 'Y'
				THEN 1
			WHEN ProblemList.HOSPITAL_PL_YN = 'N'
				THEN 0
			ELSE NULL
			END AS INTEGER) HOSPITALDIAGNOSIS
	,CAST(CASE 
			WHEN ProblemList.IS_PRESENT_ON_ADM_C IS NULL
				THEN '*Unspecified'
			WHEN PoaCategory.DX_POA_C IS NULL
				THEN '*Unknown'
			ELSE PoaCategory.NAME
			END AS VARCHAR(300)) PRESENTONADMISSION
	,CAST(CASE 
			WHEN ProblemList.CHRONIC_YN = 'Y'
				THEN 1
			WHEN ProblemList.CHRONIC_YN = 'N'
				THEN 0
			ELSE NULL
			END AS INTEGER) CHRONIC
	,edg.DX_NAME diagName
	,icd9.Code
	,icdIndex."ICD-9 Code category"
	
FROM CLARITY.DBO.PROBLEM_LIST ProblemList
LEFT OUTER JOIN CLARITY.DBO.PROBLEM_LIST_HX FirstHistory ON ProblemList.PROBLEM_LIST_ID = FirstHistory.PROBLEM_LIST_ID
	AND FirstHistory.LINE = 1
LEFT OUTER JOIN CLARITY.DBO.PAT_ENC Encounter ON FirstHistory.HX_PROBLEM_EPT_CSN = Encounter.PAT_ENC_CSN_ID
LEFT OUTER JOIN CLARITY.DBO.PAT_ENC_HSP HospitalEncounter ON FirstHistory.HX_PROBLEM_EPT_CSN = HospitalEncounter.PAT_ENC_CSN_ID
LEFT OUTER JOIN CLARITY.DBO.ZC_PROBLEM_STATUS StatusCategory ON ProblemList.PROBLEM_STATUS_C = StatusCategory.PROBLEM_STATUS_C
LEFT OUTER JOIN CLARITY.DBO.ZC_DX_POA PoaCategory ON ProblemList.IS_PRESENT_ON_ADM_C = PoaCategory.DX_POA_C
LEFT OUTER JOIN Analytics.dbo.CCDA264_CSNLookupTable csn ON FirstHistory.HX_PROBLEM_EPT_CSN = csn.PAT_ENC_CSN_ID
INNER JOIN Analytics.dbo.CCDA264_PatLookupTable pat ON pat.PAT_ID = ProblemList.PAT_ID
INNER JOIN CLARITY.dbo.CLARITY_EDG edg ON ProblemList.DX_ID = edg.DX_ID
INNER JOIN CLARITY.DBO.EDG_CURRENT_ICD9 icd9 ON ProblemList.DX_ID = icd9.DX_ID
INNER JOIN Analytics.dbo.CCDA264_ICD9Codes icdIndex ON ISNUMERIC(icd9.Code) = 1
	AND icd9.Code >= icdIndex."Low Range"
	AND icd9.Code < icdIndex."High Cutoff"
WHERE ProblemList.DX_ID IS NOT NULL
	AND NULLIF(ProblemList.PAT_ID, '') IS NOT NULL
	AND NULLIF(3, ProblemList.PROBLEM_STATUS_C) IS NOT NULL
