---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-cloudwatch-config
  namespace: kube-system
data:
  aws_region: us-east-1
  log_group: opsdx-dev-k8s-logs
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: kube-system
  labels:
    app: fluentd
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  template:
    metadata:
      labels:
        app: fluentd
        version: v1
        kubernetes.io/cluster-service: "true"
    spec:
      volumes:
      - name: pos-files
        emptyDir: {}
      - name: host-logs
        hostPath:
          path: /var/log/
      - name: docker-logs
        hostPath:
          path: /var/lib/docker
      containers:
      - image: 359300513585.dkr.ecr.us-east-1.amazonaws.com/opsdx-cluster-logging:0.0.4
        imagePullPolicy: Always
        name: fluentd
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: host-logs
          mountPath: /var/log/
        - name: docker-logs
          mountPath: /var/lib/docker/
          readOnly: true
        - name: pos-files
          mountPath: /var/pos/
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: opsdx-fluentd-secrets
              key: aws_access_key
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: opsdx-fluentd-secrets
              key: aws_secret_key
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: fluentd-cloudwatch-config
              key: aws_region
        - name: CW_LOG_GROUP
          valueFrom:
            configMapKeyRef:
              name: fluentd-cloudwatch-config
              key: log_group
