---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx-config: |-
    server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
        server_name _;
        location / {
          proxy_pass http://127.0.0.1:8000;
        }
    }
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: trews-rest-api
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: trews-rest-api
      annotations:
        scheduler.alpha.kubernetes.io/affinity: >
            {
              "podAntiAffinity": {
                "requiredDuringSchedulingIgnoredDuringExecution": [
                  {
                    "labelSelector": {
                      "matchExpressions": [
                        {
                          "key": "app",
                          "operator": "In",
                          "values": ["trews-rest-api"]
                        }
                      ]
                    },
                    "topologyKey": "kubernetes.io/hostname"
                  }
                ]
              }
            }
    spec:
      nodeSelector:
        opsdx_nodegroup: web
      containers:
      - name: trews-nginx
        image: nginx:alpine
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
        volumeMounts:
          - name: config-volume
            mountPath: "/etc/nginx/conf.d/"
      - name: trews-rest-api
        image: 359300513585.dkr.ecr.us-east-1.amazonaws.com/trews-rest-api:0.1.79
        resources:
          requests:
            memory: "2816Mi"
            cpu: "1000m"
        command:
          - "sh"
          - "start-dev.sh"
        securityContext:
          capabilities:
            add:
            - "SYS_PTRACE"
        ports:
        - containerPort: 8000
        env:
        - name: db_host
          value: "db.dev.opsdx.io"
        - name: db_port
          value: "5432"
        - name: db_name
          value: "opsdx_dev"
        - name: db_user
          valueFrom:
            secretKeyRef:
              name: rest-api-db-secrets
              key: db-username
        - name: db_password
          valueFrom:
            secretKeyRef:
              name: rest-api-db-secrets
              key: db-password
        - name: jhapi_client_id
          valueFrom:
            secretKeyRef:
              name: rest-api-db-secrets
              key: jhapi-client-id
        - name: jhapi_client_secret
          valueFrom:
            secretKeyRef:
              name: rest-api-db-secrets
              key: jhapi-client-secret
        - name: AWS_DEFAULT_REGION
          valueFrom:
            secretKeyRef:
              name: rest-api-db-secrets
              key: aws-region
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: rest-api-db-secrets
              key: aws-access-key-id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: rest-api-db-secrets
              key: aws-secret-access-key
        - name: querystring_key
          valueFrom:
            secretKeyRef:
              name: rest-api-db-secrets
              key: querystring-key
        - name: trews_app_key
          valueFrom:
            secretKeyRef:
              name: rest-api-db-secrets
              key: trews-app-key
        - name: trews_admin_key
          valueFrom:
            secretKeyRef:
              name: rest-api-db-secrets
              key: trews-admin-key
        - name: ie_mode
          value: "edge"
        - name: order_link_mode
          value: "native"
        - name: log_decryption
          value: "true"
        - name: log_user_latency
          value: "false"
        - name: trews_open_access
          value: "false"
        - name: epic_notifications
          value: "0"
        - name: logging
          value: "1"
        - name: logging_period
          value: "20"
        - name: cloudwatch_log_group
          value: "opsdx-web-logs-dev"
        - name: api_with_healthcheck
          value: "1"
        - name: api_monitor
          value: "1"
        - name: api_monitor_prometheus
          value: "0"
        - name: api_monitor_cw_push_period
          value: "10"
        - name: prometheus_multiproc_dir
          value: "/tmp"
        - name: etl_channel
          value: "on_opsdx_dev_etl"
        - name: chart_sample_start_hrs
          value: "6"
        - name: chart_sample_start_day
          value: "2"
        - name: chart_sample_end_day
          value: "7"
        - name: chart_sample_mins
          value: "30"
        - name: chart_sample_hrs
          value: "4"
      volumes:
        - name: config-volume
          configMap:
            name: nginx-config
            items:
              - key: nginx-config
                path: trews.conf
---
apiVersion: v1
kind: Service
metadata:
  name: trews-rest-svc
  labels:
    app: trews-rest-api
  annotations:
    dns.alpha.kubernetes.io/external: trews.dev.opsdx.io
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:359300513585:certificate/e8391c84-070f-4feb-8946-27cf945840ad
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
spec:
  type: LoadBalancer
  ports:
  - port: 443
    name: https
    targetPort: 80
  selector:
    app: trews-rest-api
