
---
apiVersion: v1
kind: Service
metadata:
  name: alerts
  labels:
    app: alerts
spec:
  type: NodePort
  ports:
    - name: alerts
      port: 31000
  selector:
    app: alerts
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: alerts
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: alerts
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
        scheduler.alpha.kubernetes.io/affinity: >
            {
              "podAntiAffinity": {
                "requiredDuringSchedulingIgnoredDuringExecution": [{
                  "labelSelector": {
                    "matchExpressions": [{
                      "key": "app",
                      "operator": "In",
                      "values": ["alerts"]
                    }]
                  },
                  "topologyKey": "kubernetes.io/hostname"
                }]
              }
            }
    spec:
      nodeSelector:
        opsdx_nodegroup: spot-nodes
      containers:
      - name: alerts
        image: 359300513585.dkr.ecr.us-east-1.amazonaws.com/universe:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "2Gi"
            cpu: "250m"
        command:
        - /usr/local/bin/python3
        - /etl/alerts/server.py
        ports:
          - name: alerts
            containerPort: 31000
        env:
        - name: etl_channel
          value: "on_opsdx_dev_etl"
        - name: suppression_model
          value: "lmc"
        - name: notify_web
          value: "0"
        - name: db_host
          value: "dev.db.jh.opsdx.io"
        - name: db_port
          value: "5432"
        - name: db_name
          value: "opsdx_dev"
        - name: db_user
          valueFrom:
            secretKeyRef:
              name: rest-api-db-secrets
              key: db-username
        - name: db_password
          valueFrom:
            secretKeyRef:
              name: rest-api-db-secrets
              key: db-password
        - name: AWS_DEFAULT_REGION
          valueFrom:
            secretKeyRef:
              name: rest-api-db-secrets
              key: aws-region
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: rest-api-db-secrets
              key: aws-access-key-id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: rest-api-db-secrets
              key: aws-secret-access-key
