apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    app: redash
  name: redash
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
    - host: redash-dev.jh.opsdx.io
      http:
        paths:
          - path: /
            backend:
              serviceName: redash
              servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: redash
  labels:
    app: redash
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  selector:
    app: redash
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redash
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redash
    spec:
      nodeSelector:
        opsdx_nodegroup: spot-nodes
      containers:
      - name: redash-redis
        image: redis:2.8
        ports:
          - name: redis
            containerPort: 6379
      - name: redash-server
        image: 359300513585.dkr.ecr.us-east-1.amazonaws.com/redash:0.0.3
        imagePullPolicy: Always
        resources:
          requests:
            memory: "2Gi"
            cpu: "250m"
        command:
        - /app/bin/docker-entrypoint
        - server
        ports:
          - name: proxy
            containerPort: 5000
        env:
        - name: REDASH_REDIS_URL
          value: "redis://localhost:6379/0"
        - name: REDASH_LOG_LEVEL
          value: "INFO"
        - name: REDASH_COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              name: redash-secrets
              key: redash-cookie-secret
        - name: REDASH_DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: redash-secrets
              key: db-connect-str
        - name: REDASH_MAIL_SERVER
          valueFrom:
            secretKeyRef:
              name: redash-secrets
              key: mail-server
        - name: REDASH_MAIL_USERNAME
          valueFrom:
            secretKeyRef:
              name: redash-secrets
              key: mail-username
        - name: REDASH_MAIL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redash-secrets
              key: mail-password
        - name: REDASH_MAIL_DEFAULT_SENDER
          valueFrom:
            secretKeyRef:
              name: redash-secrets
              key: mail-default-sender
        - name: REDASH_MAIL_PORT
          value: "587"
        - name: REDASH_MAIL_USE_TLS
          value: "true"
        - name: REDASH_MAIL_USE_SSL
          value: "false"
        - name: REDASH_HOST
          value: "https://redash-dev.jh.opsdx.io"
      - name: redash-worker
        image: 359300513585.dkr.ecr.us-east-1.amazonaws.com/redash:0.0.3
        imagePullPolicy: Always
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
        command:
        - /app/bin/docker-entrypoint
        - scheduler
        env:
        - name: REDASH_REDIS_URL
          value: "redis://localhost:6379/0"
        - name: REDASH_LOG_LEVEL
          value: "INFO"
        - name: REDASH_DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: redash-secrets
              key: db-connect-str
        - name: QUEUES
          value: "queries,scheduled_queries,celery"
        - name: WORKERS_COUNT
          value: "2"
