---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opsdx-nfs-server-storage
  annotations:
    volume.beta.kubernetes.io/storage-class: ebs-pv
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 500Gi
---
kind: Service
apiVersion: v1
metadata:
  name: nfs-server
  labels:
    app: nfs-server
spec:
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
  type: NodePort
  selector:
    app: nfs-server
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: nfs-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nfs-server
    spec:
      nodeSelector:
        opsdx_nodegroup: nodes
      containers:
        - name: nfs-server
          image: 359300513585.dkr.ecr.us-east-1.amazonaws.com/trews-nginx:nfs
          resources:
            requests:
              memory: "1Gi"
              cpu: "250m"
          ports:
            - name: nfs
              containerPort: 2049
            - name: mountd
              containerPort: 20048
            - name: rpcbind
              containerPort: 111
          securityContext:
            privileged: true
          imagePullPolicy: "Always"
          volumeMounts:
            - name: export-volume
              mountPath: /exports
      volumes:
        - name: export-volume
          persistentVolumeClaim:
            claimName: opsdx-nfs-server-storage
