---
apiVersion: v1
kind: ConfigMap
metadata:
  name: jupyterhub-config-py
data:
  jupyterhub-config.py: |-
    c = get_config()
    import os
    c.JupyterHub.ip = '0.0.0.0'
    c.JupyterHub.hub_ip = '0.0.0.0'
    c.JupyterHub.extra_log_file = '/var/log/jupyterhub.log'
    c.JupyterHub.db_url = 'sqlite:////tmp/jupyterhub.sqlite'
    c.JupyterHub.cookie_secret_file = '/tmp/jupyterhub_cookie_secret'
    c.JupyterHub.cleanup_servers = False
    # No SSL, rely on LB termination
    c.JupyterHub.confirm_no_ssl = True
    # Github Authenticator
    c.JupyterHub.authenticator_class = 'oauthenticator.GitHubOAuthenticator'
    c.GitHubOAuthenticator.client_id = os.environ['OAUTH_CLIENT_ID']
    c.GitHubOAuthenticator.client_secret = os.environ['OAUTH_CLIENT_SECRET']
    c.GitHubOAuthenticator.oauth_callback_url = os.environ['OAUTH_CALLBACK_URL']
    c.Authenticator.whitelist = { 'yanif', 'zad', 'mpeven', 'benring' }
    # Kube Spawner
    c.JupyterHub.spawner_class = 'kubespawner.KubeSpawner'
    #c.KubeSpawner.namespace = 'jupyterhub'
    c.KubeSpawner.hub_connect_ip = os.environ['KSPAWN_HUB_IP']
    c.KubeSpawner.hub_connect_port = int(os.environ['KSPAWN_HUB_PORT'])
    c.KubeSpawner.start_timeout = 60 * 5
    c.KubeSpawner.singleuser_uid = 0
    c.KubeSpawner.singleuser_image_spec = os.environ['KSPAWN_IMAGE']
    c.KubeSpawner.cpu_limit = float(os.environ['KSPAWN_CPU_LIMIT'])
    c.KubeSpawner.mem_limit = os.environ['KSPAWN_MEM_LIMIT']
    # Each user gets their own persistentVolumeClaim
    c.KubeSpawner.environment = dict(GRANT_SUDO='yes', NOTEBOOK_DIR=lambda sp: sp.format_string('/home/{username}/notebooks'))
    c.KubeSpawner.user_storage_capacity = '100Mi'
    c.KubeSpawner.user_storage_class = 'opsdx-nfs'
    c.KubeSpawner.volumes = [{
        'name' : 'notebook-volume',
        'persistentVolumeClaim' : {
            'claimName' : 'claim-{username}-{userid}',
        },
    }]
    c.KubeSpawner.volume_mounts = [{
        'name' : 'notebook-volume',
        'mountPath' : '/home/{username}/notebooks',
    }]
    c.KubeSpawner.with_api_access = True
    if 'KSPAWN_NODE_SELECTOR' in os.environ and os.environ['KSPAWN_NODE_SELECTOR']:
        c.KubeSpawner.node_selector = dict((k,v) for k, v in (kv.split(':') for kv in os.environ['KSPAWN_NODE_SELECTOR'].split(',')))
---
apiVersion: v1
kind: Service
metadata:
  name: jupyterhub
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:359300513585:certificate/e8391c84-070f-4feb-8946-27cf945840ad
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
  labels:
    app: jupyterhub
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 443
      targetPort: 8000
  selector:
    app: jupyterhub
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jupyterhub
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jupyterhub
    spec:
      containers:
      - name: jupyterhub
        image: jupyterhub/jupyterhub
        ports:
          - name: proxy
            containerPort: 8000
        command:
        - sh
        - -c
        - pip install git+git://github.com/yanif/kubespawner.git oauthenticator && jupyterhub
        env:
        - name: KSPAWN_HUB_IP
          value: "jupyterhub.default.svc.cluster.local"
        - name: KSPAWN_HUB_PORT
          value: "443"
        - name: KSPAWN_IMAGE
          value: '359300513585.dkr.ecr.us-east-1.amazonaws.com/tensorflow:tfplus.0.0.2'
        - name: KSPAWN_CPU_LIMIT
          value: '1'
        - name: KSPAWN_CPU_REQUEST
          value: '1'
        - name: KSPAWN_MEM_LIMIT
          value: '2G'
        - name: KSPAWN_MEM_REQUEST
          value: '256M'
        #- name: KSPAWN_NODE_SELECTOR
        #  value: 'opsdx/role:tf-train'
        - name: OAUTH_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: jupyterhub-secrets
              key: oauth-client-id
        - name: OAUTH_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: jupyterhub-secrets
              key: oauth-client-secret
        - name: OAUTH_CALLBACK_URL
          valueFrom:
            secretKeyRef:
              name: jupyterhub-secrets
              key: oauth-callback-url
        volumeMounts:
          - name: config-volume
            mountPath: "/srv/jupyterhub/"
      volumes:
        - name: config-volume
          configMap:
            name: jupyterhub-config-py
            items:
              - key: jupyterhub-config.py
                path: jupyterhub_config.py