---
apiVersion: batch/v1
kind: Job
metadata:
  name: dw-s3-export
spec:
  template: # create pods using pod definition in this template
    metadata:
      name: dw-s3-export
      namespace: default
    spec:
      restartPolicy: Never
      nodeSelector:
        opsdx_nodegroup: spot-nodes
      containers:
      - name: universe
        image: 359300513585.dkr.ecr.us-east-1.amazonaws.com/universe:1.0.94
        imagePullPolicy: IfNotPresent
        command:
          - sh
          - -c
          - "aws s3 cp s3://opsdx-deployment/scripts/dw-s3-export.sh /tmp && chmod 755 /tmp/dw-s3-export.sh && /tmp/dw-s3-export.sh"
        env:
        #- name: export_tables
        #  value: "public.dw_version"
        # For exporting queries.
        - name: export_tables ## Must be set, but empty when using an export_query (for now).
          value: ""
        - name: export_query
          value: "select dataset_id, enc_id, tsp::timestamptz(0), pao2, pao2_c, hepatic_sofa, hepatic_sofa_c, paco2, paco2_c, abp_mean, abp_mean_c, sodium, sodium_c, obstructive_pe_shock, obstructive_pe_shock_c, metabolic_acidosis, metabolic_acidosis_c, troponin, troponin_c, rass, rass_c, sirs_raw, sirs_raw_c, pao2_to_fio2, pao2_to_fio2_c, qsofa, qsofa_c, fio2, fio2_c, neurologic_sofa, neurologic_sofa_c, hematologic_sofa, hematologic_sofa_c, renal_sofa, renal_sofa_c, nbp_sys, nbp_sys_c, sirs_hr_oor, sirs_hr_oor_c, resp_sofa, resp_sofa_c, bun_to_cr, bun_to_cr_c, cmi, cmi_c, cardio_sofa, cardio_sofa_c, acute_pancreatitis, acute_pancreatitis_c, wbc, wbc_c, shock_idx, shock_idx_c, weight, weight_c, platelets, platelets_c, arterial_ph, arterial_ph_c, nbp_dias, nbp_dias_c, fluids_intake_1hr, fluids_intake_1hr_c, co2, co2_c, dbpm, dbpm_c, ddimer, ddimer_c, ast_liver_enzymes, ast_liver_enzymes_c, fluids_intake_24hr, fluids_intake_24hr_c, ptt, ptt_c, abp_sys, abp_sys_c, magnesium, magnesium_c, severe_sepsis, severe_sepsis_c, bicarbonate, bicarbonate_c, lipase, lipase_c, hypotension_raw, hypotension_raw_c, sbpm, sbpm_c, heart_rate, heart_rate_c, nbp_mean, nbp_mean_c, anion_gap, anion_gap_c, vasopressor_resuscitation, vasopressor_resuscitation_c, urine_output_24hr, urine_output_24hr_c, amylase, amylase_c, septic_shock_iii, septic_shock_iii_c, hematocrit, hematocrit_c, temperature, temperature_c, sirs_wbc_oor, sirs_wbc_oor_c, hemoglobin_minutes_since_measurement, hemoglobin_minutes_since_measurement_c, urine_output_6hr, urine_output_6hr_c, chloride, chloride_c, spo2, spo2_c, resp_rate, resp_rate_c, hemorrhagic_shock, hemorrhagic_shock_c, potassium, potassium_c, acute_liver_failure, acute_liver_failure_c, bun, bun_c, hemoglobin_change, hemoglobin_change_c, mi, mi_c, hypotension_intp, hypotension_intp_c, calcium, calcium_c, abp_dias, abp_dias_c, acute_organ_failure, acute_organ_failure_c, worst_sofa, worst_sofa_c, hemoglobin, hemoglobin_c, any_organ_failure, any_organ_failure_c, inr, inr_c, creatinine, creatinine_c, fluid_resuscitation, fluid_resuscitation_c, bilirubin, bilirubin_c, alt_liver_enzymes, alt_liver_enzymes_c, mapm, mapm_c, map, map_c, gcs, gcs_c, sirs_intp, sirs_intp_c, minutes_since_any_antibiotics, minutes_since_any_antibiotics_c, fluids_intake_3hr, fluids_intake_3hr_c, sirs_temperature_oor, sirs_temperature_oor_c, sirs_resp_oor, sirs_resp_oor_c, septic_shock, septic_shock_c, lactate, lactate_c, minutes_since_any_organ_fail, minutes_since_any_organ_fail_c from cdm_twf"
        - name: query_id
          value: "public.cdm_twf"
        - name: output_dir
          value: "dw-s3-export"
        - name: db_host
          value: "dw.jh.opsdx.io"
        - name: db_port
          value: "5432"
        - name: db_name
          value: "opsdx_dev_dw"
        - name: db_user
          valueFrom:
            secretKeyRef:
              name: dw-s3-export-secrets
              key: db-username
        - name: db_password
          valueFrom:
            secretKeyRef:
              name: dw-s3-export-secrets
              key: db-password
        - name: AWS_DEFAULT_REGION
          valueFrom:
            secretKeyRef:
              name: dw-s3-export-secrets
              key: aws-region
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: dw-s3-export-secrets
              key: aws-access-key-id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: dw-s3-export-secrets
              key: aws-secret-access-key
        securityContext:
          privileged: true
