
---
apiVersion: v1
kind: Service
metadata:
  name: alerts
  labels:
    app: alerts
spec:
  type: NodePort
  ports:
    - name: alerts
      port: 31000
  selector:
    app: alerts
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: alerts
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: alerts
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
        scheduler.alpha.kubernetes.io/affinity: >
            {
              "podAntiAffinity": {
                "requiredDuringSchedulingIgnoredDuringExecution": [{
                  "labelSelector": {
                    "matchExpressions": [{
                      "key": "app",
                      "operator": "In",
                      "values": ["alerts"]
                    }]
                  },
                  "topologyKey": "kubernetes.io/hostname"
                }]
              }
            }
    spec:
      nodeSelector:
        opsdx_nodegroup: nodes
      containers:
      - name: alerts
        image: 359300513585.dkr.ecr.us-east-1.amazonaws.com/trews-etl:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "2Gi"
            cpu: "250m"
        command:
        - /usr/local/bin/python3
        - /dashan-etl/etl/alerts/server.py
        ports:
          - name: alerts
            containerPort: 31000
