-- flowsheet.sql
SELECT IDENTITY_ID.IDENTITY_ID pat_id
    ,PAT_ENC_HSP.PAT_ENC_CSN_ID
    ,IP_FLO_GP_DATA.FLO_MEAS_NAME
    ,IP_FLO_GP_DATA.DISP_NAME
    ,IP_FLWSHT_MEAS.FLO_MEAS_ID
    ,rowtype.NAME ROW_TYPE
    ,intakeType.NAME INTAKE_TYPE
    ,outputType.NAME OUTPUT_TYPE
    ,IP_FLWSHT_MEAS.RECORDED_TIME TimeTaken
    ,CASE
        WHEN IP_FLO_GP_DATA.val_type_c = 5
            THEN convert(FLOAT, IP_FLWSHT_MEAS.MEAS_VALUE) / 16.0
        ELSE NULL
        END ConvertedWeightValue
    ,meas_value Value
    ,IP_FLO_GP_DATA.UNITS
    ,flt.TEMPLATE_ID
    ,flt.TEMPLATE_NAME
    ,flt.DISPLAY_NAME TEMPLATE_DISP_NAME
FROM CLARITY.dbo.IP_FLWSHT_MEAS IP_FLWSHT_MEAS
INNER JOIN CLARITY.dbo.IP_FLO_GP_DATA IP_FLO_GP_DATA ON IP_FLWSHT_MEAS.FLO_MEAS_ID = IP_FLO_GP_DATA.FLO_MEAS_ID
INNER JOIN CLARITY.dbo.IP_FLWSHT_REC IP_FLWSHT_REC ON IP_FLWSHT_MEAS.FSD_ID = IP_FLWSHT_REC.FSD_ID
LEFT JOIN CLARITY.DBO.IP_FLOWSHEET_ROWS RWS ON RWS.LINE = IP_FLWSHT_MEAS.OCCURANCE
    AND IP_FLWSHT_MEAS.FSD_ID = RWS.INPATIENT_DATA_ID
-----------------------
-- get pat_id
INNER JOIN CLARITY.dbo.PAT_ENC_HSP ON IP_FLWSHT_REC.INPATIENT_DATA_ID = PAT_ENC_HSP.INPATIENT_DATA_ID
INNER JOIN IDENTITY_ID on IDENTITY_ID.PAT_ID = PAT_ENC_HSP.PAT_ID
-----------------------
LEFT JOIN CLARITY.dbo.IP_FLT_DATA flt ON flt.TEMPLATE_ID = IP_FLWSHT_MEAS.FLT_ID
LEFT JOIN CLARITY.DBO.ZC_ROW_TYP rowtype ON rowtype.ROW_TYP_C = ip_flo_gp_data.ROW_TYP_C
LEFT JOIN CLARITY.DBO.ZC_INTAKE_TYPE_P intakeType ON intakeType.INTAKE_TYPe_P_C = ip_flo_gp_data.INTAKE_TYP_C
LEFT JOIN CLARITY.DBO.ZC_OUTPUT_TYPE_P outputType ON outputType.OUTPUT_TYPE_P_C = ip_flo_gp_data.OUTPUT_TYP_C
WHERE
IDENTITY_ID.line = 1
-- limit timestamp to be 72 hours until now
AND IP_FLWSHT_MEAS.RECORDED_TIME >= DATEADD(hh, -72, GETDATE())

-- only query HCGH patients
and PAT_ENC_HSP.DEPARTMENT_ID like '1103%'
