---
# add by andong
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prom-gateway
  namespace: monitoring
  labels:
    name: prom-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      name: prom-gateway
  template:
    metadata:
      labels:
        name: prom-gateway
    spec:
      containers:
      - name: prom-gateway
        image: prom/pushgateway
        ports:
          - containerPort: 9091
---
# added by andong
apiVersion: v1
kind: Service
metadata:
  name: prom-gateway
  namespace: monitoring
  labels:
    name: prom-gateway
spec:
  type: LoadBalancer
  ports:
    - port: 9091
  selector:
    name: prom-gateway
