Name: locust

image:
  repository: quay.io/honestbee/locust
  tag: 0.7.5
  pullPolicy: IfNotPresent

service:
  name: master-web
  type: NodePort
  externalPort: 8089
  internalPort: 8089
  nodePort: 0
master:
  config:
    target-host: https://trews.dev.opsdx.io
  nodeSelector:
    opsdx_nodegroup: locust
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
worker:
  config:

    # all files from tasks folder are mounted under `/locust-tasks`
    locust-script: "/locust-tasks/trews.py"
  nodeSelector:
    opsdx_nodegroup: locust
  replicaCount: 4
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

