"""
diag, hist, and prob are not included in this cdm_defs
"""
cdm_defs = {
    'abp': {
        'unit':     'mmHg',
        'value':    str,
        'thresh':   (None, None),
        'human_readable':   'Arterial Blood Pressure',
    },
    'abp_dias': {
        'unit':     'mmHg',
        'value':    float,
        'thresh':   (8, 150),
        'human_readable':   'Diastolic Arterial BP',
    },
    'abp_sys': {
        'unit':     'mmHg',
        'value':    float,
        'thresh':   (30, 250),
        'human_readable':   'Systolic Arterial BP',
    },
    'albumin_dose': {
        'unit':     '',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Albumin',
    },
    'acebutolol_dose': {
        'unit':     '',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Acebutolol',
    },
    'aminoglycosides_dose': {
        'unit':     '',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Aminoglycosides',
    },
    'alt_liver_enzymes': {
        'unit':     'Units/L',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'ALT Liver Enzymes',
    },
    'amlodipine_dose': {
        'unit':     'mg',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Amlodipine',
    },
    'amoxicillin_dose': {
        'unit':     'mg',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Amoxicillin',
    },
    'ampicillin_dose': {
        'unit':     'mg',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Ampicillin',
    },
    'amylase': {
        'unit':     'Units/L',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Amylase',
    },
    'arterial_ph': {
        'unit':     '',
        'value':    float,
        'thresh':   (6.5, 8.5),
        'human_readable':   'Arterial pH',
    },
    'ast_liver_enzymes': {
        'unit':     'Units/L',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'AST Liver Enzymes',
    },
    'atenolol_dose': {
        'unit':     '',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Atenolol',
    },
    'atorvastatin_dose': {
        'unit':     '',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Atorvastatin',
    },
    'azithromycin_dose': {
        'unit':     '',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Azithromycin',
    },
    'aztreonam_dose': {
        'unit':     '',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Aztreonam',
    },
    'bands': {
        'unit':     '%',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Bands',
    },
    'benazepril_dose': {
        'unit':     '',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Benazepril',
    },
    'bilirubin': {
        'unit':     'mg/dL',
        'value':    float,
        'thresh':   (0, 50),
        'human_readable':   'Bilirubin',
    },
    'bicarbonate': {
        'unit':     'mmol/L',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Bicarbonate',
    },
    'bipap': {
        'unit':     '',
        'value':    None,
        'thresh':   (None, None),
        'human_readable':   'Bipap',
    },
    'bisoprolol_dose': {
        'unit':     '',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Bisoprolol',
    },
    'blood_culture': {
        'unit':     '',
        'value':    None,
        'thresh':   (None, None),
        'human_readable':   'Blood Cultures',
    },
    'bun': {
        'unit':     'mg/dL',
        'value':    float,
        'thresh':   (0.1, 180),
        'human_readable':   'BUN',
    },
    'bun_to_cr': {
        'unit':     'Ratio',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'BUN to Creatinine Ratio',
    },
    'captopril_dose': {
        'unit':     '',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Captopril',
    },
    'cefazolin_dose': {
        'unit':     'mg',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Cefazolin',
    },
    'cefepime_dose': {
        'unit':     'mg',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Cefepime',
    },
    'ceftazidime_dose': {
        'unit':     'mg',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Ceftazidime',
    },
    'ceftriaxone_dose': {
        'unit':     'mg',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Ceftriaxone',
    },
    'cephalosporins_1st_gen_dose': {
        'unit':     '',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Cephalosporins 1ST Generation',
    },
    'cephalosporins_2nd_gen_dose': {
        'unit':     '',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Cephalosporins 2ND Generation',
    },
    'ciprofloxacin_dose': {
        'unit':     'mg',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Ciprofloxacin',
    },
    'clindamycin_dose': {
        'unit':     'mg',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Clindamycin',
    },
    'cms_antibiotics': {
        'unit':     'mg',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Sepsis Antibiotics Bundle',
    },
    'co2': {
        'unit':     'mmol/L',
        'value':    float,
        'thresh':   (0.1, 55),
        'human_readable':   'CO2',
    },
    'cpap': {
        'unit':     '',
        'value':    None,
        'thresh':   (None, None),
        'human_readable':   'Cpap',
    },
    'creatinine': {
        'unit':     'mg/dL',
        'value':    float,
        'thresh':   (0.1, 40),
        'human_readable':   'Creatinine',
    },
    'crystalloid_fluid': {
        'unit':     'ml',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Total Crystalloid Fluid',
    },
    'daptomycin_dose': {
        'unit':     '',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Dopamine'
    },
    'dextrose_water': {
        'unit':     'ml',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Dextrose Water',
    },
    'dextrose_normal_saline': {
        'unit':     'ml',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Dextrose Normal Saline',
    },
    'ddimer': {
        'unit':     'mg/L FEU',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'D-Dimer'
    },
    'dialysis': {
        'unit':     'ml',
        'value':    float,
        'thresh':   (0.01, None),
        'human_readable':   'Dialysis'
    },
    'dobutamine_dose': {
        'unit':     'mcg/kg/min',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Dobutamine',
    },
    'diltiazem_dose': {
        'unit':     'mg',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Diltiazem',
    },
    'dopamine_dose': {
        'unit':     'mcg/kg/min',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Dopamine',
    },
    'enalapril_dose': {
        'unit':     'mg',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Epinephrine',
    },
    'enalaprilat_dose': {
        'unit':     'mg',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Epinephrine',
    },
    'epinephrine_dose': {
        'unit':     'mcg/kg/min',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Epinephrine',
    },
    'erythromycin_dose': {
        'unit':     'mg',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Erythromycin',
    },
    'ezetimibe_dose': {
        'unit':     'mg',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Ezetimibe',
    },
    'fio2': {
        'unit':     '%',
        'value':    float,
        'thresh':   (20, 100),
        'human_readable':   'FiO2',
    },
    'fluids_intake': {
        'unit':     'ml',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Total Fluid Intake',
    },
    'gcs': {
        'unit':     '',
        'value':    float,
        'thresh':   (3, 15),
        'human_readable':   'GCS',
    },
    'gentamicin_dose': {
        'unit':     'mg',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Gentamicin',
    },
    'glycopeptides_dose': {
        'unit':     '',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Glycopeptides'
    },
    'heart_rate': {
        'unit':     'beats per min',
        'value':    float,
        'thresh':   (20, 300),
        'human_readable':   'Heart Rate',
    },
    'hemoglobin': {
        'unit':     'g/dL',
        'value':    float,
        'thresh':   (4, 20),
        'human_readable':   'Hemoglobin',
    },
    'heparin_dose': {
        'unit':     'mg',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Heparin',
    },
    'hetastarch': {
        'unit':     '',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Hetastarch',
    },
    'inr': {
        'unit':     'Ratio',
        'value':    float,
        'thresh':   (0.01, 12),
        'human_readable':   'INR',
    },
    'lactate': {
        'unit':     'mmol/L',
        'value':    float,
        'thresh':   (0.2, 40),
        'human_readable':   'Lactate',
    },
    'lactated_ringers': {
        'unit':     'ml',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Lactated Ringers',
    },
    'levofloxacin_dose': {
        'unit':     'mg',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Levofloxacin',
    },
    'levophed_infusion_dose': {
        'unit':     'mcg/kg/min',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Levophed',
    },
    'lipase': {
        'unit':     'Units/L',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Lipase',
    },
    'lisinopril_dose': {
        'unit':     'mg',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Lisinopril',
    },
    'linezolid_dose': {
        'unit':     '',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Linezolid'
    },
    'macrolides_dose': {
        'unit':     '',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Macrolides'
    },
    'map': {
        'unit':     'mmHg',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'MAP',
    },
    'mapm': {
        'unit':     'mmHg',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'MAPM',
    },
    'meropenem_dose': {
        'unit':     'mg',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Meropenem',
    },
    'metoprolol_dose': {
        'unit':     '',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Metoprolol',
    },
    'metronidazole_dose': {
        'unit':     'mg',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Metronidazole',
    },
    'milrinone_dose': {
        'unit':     '',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Milrinone',
    },
    'moxifloxacin_dose': {
        'unit':     'mg',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Moxifloxacin',
    },
    'nadolol_dose': {
        'unit':     '',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Moxifloxacin',
    },
    'nbp': {
        'unit':     'mmHg',
        'value':    str,
        'thresh':   (None, None),
        'human_readable':   'Blood Pressure',
    },
    'nbp_dias': {
        'unit':     'mmHg',
        'value':    float,
        'thresh':   (8, 150),
        'human_readable':   'Non-invasive Diastolic BP',
    },
    'nbp_sys': {
        'unit':     'mmHg',
        'value':    float,
        'thresh':   (30, 250),
        'human_readable':   'Non-invasive Systolic BP',
    },
    'neosynephrine_dose': {
        'unit':     '',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Neo-Synephrine',
    },
    'nicardipine_dose': {
        'unit':     '',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Nicardipine',
    },
    'nifedipine_dose': {
        'unit':     '',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Nifedipine',
    },
    'norepinephrine_dose': {
        'unit':     '',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Norepinephrine',
    },
    'oxacillin_dose': {
        'unit':     'mg',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Oxacillin',
    },
    'paco2': {
        'unit':     'mmHg',
        'value':    float,
        'thresh':   (5, 100),
        'human_readable':   'PaCO2',
    },
    'pao2': {
        'unit':     'mmHg',
        'value':    float,
        'thresh':   (0.1, 500),
        'human_readable':   'PaO2',
    },
    'penicillin_dose': {
        'unit':     'Million Units',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Penicillin',
    },
    'penicillin_g_dose': {
        'unit':     'Million Units',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Penicillin G',
    },
    'piperacillin_tazobac_dose': {
        'unit':     'mg',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Piperacillin/tazobactam',
    },
    'platelets': {
        'unit':     '1000/uL',
        'value':    float,
        'thresh':   (0.1, 1200),
        'human_readable':   'Platelets',
    },
    'ptt': {
        'unit':     'Seconds',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Partial thromboplastin time (PTT)',
    },
    'pravastatin_dose': {
        'unit':     'mg',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Pravastatin',
    },
    'propofol_dose': {
        'unit':     'mg',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Propofol',
    },
    'propranolol_dose': {
        'unit':     '',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Propofol',
    },
    'rapamycin_dose': {
        'unit':     'mg',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Rapamycin',
    },
    'rass': {
        'unit':     '',
        'value':    str,
        'thresh':   (None, None),
        'human_readable':   'RASS',
    },
    'resp_rate': {
        'unit':     'breath per min',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Respiratory Rate',
    },
    'rifampin_dose': {
        'unit':     'mg',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Rifampin',
    },
    'rosuvastatin_dose': {
        'unit':     'mg',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Rosuvastatin',
    },
    'simvastatin_dose': {
        'unit':     'mg',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Simvastatin',
    },
    'sodium': {
        'unit':     'mmol/L',
        'value':    float,
        'thresh':   (115, 160),
        'human_readable':   'Sodium',
    },
    'sodium_bicarbonate': {
        'unit':     'ml',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Sodium Bicarbonate',
    },
    'sodium_chloride': {
        'unit':     'ml',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Saline',
    },
    'spo2': {
        'unit':     '%',
        'value':    float,
        'thresh':   (0, 100),
        'human_readable':   'SpO2',
    },
    'tobramycin_dose': {
        'unit':     'mg',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Tobramycin',
    },
    'temperature': {
        'unit':     'Fahrenheit',
        'value':    float,
        'thresh':   (80, 110),
        'human_readable':   'Temperature',
    },
    'tobramycin_dose': {
        'unit':     'mg',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Tobramycin',
    },
    'urine_output': {
        'unit':     'ml',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Urine Output',
    },
    'vancomycin_dose': {
        'unit':     'mg',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Vancomycin',
    },
    'vasopressin_dose': {
        'unit':     '',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Vasopressin',
    },
    'vasopressors_dose': {
        'unit':     '',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Vasopressors',
    },
    'vent': {
        'unit':     '',
        'value':    str,
        'thresh':   (None, None),
        'human_readable':   'Mechanical Ventilation',
    },
    'verapamil_dose': {
        'unit':     'mg',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Verapamil',
    },
    'warfarin_dose': {
        'unit':     'mg',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Warfarin',
    },
    'wbc': {
        'unit':     '1000/uL',
        'value':    float,
        'thresh':   (0.1, 70),
        'human_readable':   'WBC',
    },
    'weight': {
        'unit':     'kg',
        'value':    float,
        'thresh':   (0.1, 300),
        'human_readable':   'Weight',
    },
    'influanat': {
        'unit':     '',
        'value':    str,
        'thresh':   (None, None),
        'human_readable':   'Influanat',
    },
    'influbnat': {
        'unit':     '',
        'value':    str,
        'thresh':   (None, None),
        'human_readable':   'Influbnat',
    },
    'rsvnat': {
        'unit':     '',
        'value':    str,
        'thresh':   (None, None),
        'human_readable':   'rsvnat',
    },
}
