cdm_defs = {
    'albumin_dose': {
        'unit':     '',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Albumin',
    },
    'amoxicillin_dose': {
        'unit':     'mg',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Amoxicillin',
    },
    'ampicillin_dose': {
        'unit':     'mg',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Ampicillin',
    },
    'amylase': {
        'unit':     'Units/L',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Amylase',
    },
    'arterial_ph': {
        'unit':     '',
        'value':    float,
        'thresh':   (6.5, 8.5),
        'human_readable':   'Arterial pH',
    },
    'ast_liver_enzymes': {
        'unit':     'Units/L',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'AST Liver Enzymes',
    },
    'azithromycin_dose': {
        'unit':     '',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Azithromycin',
    },
    'aztronam_dose': {
        'unit':     '',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Aztronam',
    },
    'bands': {
        'unit':     '%',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Bands',
    },
    'bilirubin': {
        'unit':     'mg/dL',
        'value':    float,
        'thresh':   (0, 50),
        'human_readable':   'Bilirubin',
    },
    'blood_culture': {
        'unit':     '',
        'value':    None,
        'thresh':   (None, None),
        'human_readable':   'Blood Cultures',
    },
    'bun': {
        'unit':     'mg/dL',
        'value':    float,
        'thresh':   (0.1, 180),
        'human_readable':   'BUN',
    },
    'bun_to_cr': {
        'unit':     'Ratio',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'BUN to Creatinine Ratio',
    },
    'cefazolin_dose': {
        'unit':     'mg',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Cefazolin',
    },
    'cefepime_dose': {
        'unit':     'mg',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Cefepime',
    },
    'ceftazidime_dose': {
        'unit':     'mg',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Ceftazidime',
    },
    'ceftriaxone_dose': {
        'unit':     'mg',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Ceftriaxone',
    },
    'ciprofloxacin_dose': {
        'unit':     'mg',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Ciprofloxacin',
    },
    'clindamycin_dose': {
        'unit':     'mg',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Clindamycin',
    },
    'cms_antibiotics': {
        'unit':     'mg',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Sepsis Antibiotics Bundle',
    },
    'co2': {
        'unit':     'mmol/L',
        'value':    float,
        'thresh':   (0.1, 55),
        'human_readable':   'CO2',
    },
    'creatinine': {
        'unit':     'mg/dL',
        'value':    float,
        'thresh':   (0.1, 40),
        'human_readable':   'Creatinine',
    },
    'crystalloid_fluid': {
        'unit':     'ml',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Total Crystalloid Fluid',
    },
    'dobutamine_dose': {
        'unit':     'mcg/kg/min',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Dobutamine',
    },
    'dopamine_dose': {
        'unit':     'mcg/kg/min',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Dopamine',
    },
    'epinephrine_dose': {
        'unit':     'mcg/kg/min',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Epinephrine',
    },
    'erythromycin_dose': {
        'unit':     'mg',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Erythromycin',
    },
    'fio2': {
        'unit':     '%',
        'value':    float,
        'thresh':   (20, 100),
        'human_readable':   'FiO2',
    },
    'fluids_intake': {
        'unit':     'ml',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Total Fluid Intake',
    },
    'gcs': {
        'unit':     '',
        'value':    float,
        'thresh':   (3, 15),
        'human_readable':   'GCS',
    },
    'gentamicin_dose': {
        'unit':     'mg',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Gentamicin',
    },
    'heart_rate': {
        'unit':     'beats per min',
        'value':    float,
        'thresh':   (20, 300),
        'human_readable':   'Heart Rate',
    },
    'hemoglobin': {
        'unit':     'g/dL',
        'value':    float,
        'thresh':   (4, 20),
        'human_readable':   'Hemoglobin',
    },
    'hetastarch': {
        'unit':     '',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Hetastarch',
    },
    'inr': {
        'unit':     'Ratio',
        'value':    float,
        'thresh':   (0.01, 12),
        'human_readable':   'INR',
    },
    'lactate': {
        'unit':     'mmol/L',
        'value':    float,
        'thresh':   (0.2, 40),
        'human_readable':   'Lactate',
    },
    'lactated_ringers': {
        'unit':     '',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Lactated Ringers',
    },
    'levofloxacin_dose': {
        'unit':     'mg',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Levofloxacin',
    },
    'levophed_infusion_dose': {
        'unit':     'mcg/kg/min',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Levophed',
    },
    'lipase': {
        'unit':     'Units/L',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Lipase',
    },
    'mapm': {
        'unit':     'mmHg',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'MAP',
    },
    'meropenem_dose': {
        'unit':     'mg',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Meropenem',
    },
    'metronidazole_dose': {
        'unit':     'mg',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Metronidazole',
    },
    'milrinone_dose': {
        'unit':     '',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Milrinone',
    },
    'moxifloxacin_dose': {
        'unit':     'mg',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Moxifloxacin',
    },
    'nbp': {
        'unit':     'mmHg',
        'value':    str,
        'thresh':   (None, None),
        'human_readable':   'Blood Pressure',
    },
    'nbp_dias': {
        'unit':     'mmHg',
        'value':    float,
        'thresh':   (8, 150),
        'human_readable':   'Non-invasive Diastolic BP',
    },
    'nbp_sys': {
        'unit':     'mmHg',
        'value':    float,
        'thresh':   (30, 250),
        'human_readable':   'Non-invasive Systolic BP',
    },
    'abp': {
        'unit':     'mmHg',
        'value':    str,
        'thresh':   (None, None),
        'human_readable':   'Arterial Blood Pressure',
    },
    'abp_dias': {
        'unit':     'mmHg',
        'value':    float,
        'thresh':   (8, 150),
        'human_readable':   'Diastolic Arterial BP',
    },
    'abp_sys': {
        'unit':     'mmHg',
        'value':    float,
        'thresh':   (30, 250),
        'human_readable':   'Systolic Arterial BP',
    },
    'neosynephrine_dose': {
        'unit':     '',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Neo-Synephrine',
    },
    'oxacillin_dose': {
        'unit':     'mg',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Oxacillin',
    },
    'paco2': {
        'unit':     'mmHg',
        'value':    float,
        'thresh':   (5, 100),
        'human_readable':   'PaCO2',
    },
    'pao2': {
        'unit':     'mmHg',
        'value':    float,
        'thresh':   (0.1, 500),
        'human_readable':   'PaO2',
    },
    'penicillin_dose': {
        'unit':     'Million Units',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Penicillin',
    },
    'piperacillin_tazbac_dose': {
        'unit':     'mg',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Piperacillin/tazobactam',
    },
    'platelets': {
        'unit':     '1000/uL',
        'value':    float,
        'thresh':   (0.1, 1200),
        'human_readable':   'Platelets',
    },
    'ptt': {
        'unit':     'Seconds',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Partial thromboplastin time (PTT)',
    },
    'rapamycin_dose': {
        'unit':     'mg',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Rapamycin',
    },
    'rass': {
        'unit':     '',
        'value':    str,
        'thresh':   (None, None),
        'human_readable':   'RASS',
    },
    'resp_rate': {
        'unit':     'breath per min',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Respiratory Rate',
    },
    'rifampin_dose': {
        'unit':     'mg',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Rifampin',
    },
    'sodium': {
        'unit':     'mmol/L',
        'value':    float,
        'thresh':   (115, 160),
        'human_readable':   'Sodium',
    },
    'sodium_chloride': {
        'unit':     '',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Saline',
    },
    'spo2': {
        'unit':     '%',
        'value':    float,
        'thresh':   (0, 100),
        'human_readable':   'SpO2',
    },
    'temperature': {
        'unit':     'Fahrenheit',
        'value':    float,
        'thresh':   (80, 110),
        'human_readable':   'Temperature',
    },
    'tobramycin_dose': {
        'unit':     'mg',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Tobramycin',
    },
    'urine_output': {
        'unit':     'ml',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Urine Output',
    },
    'vancomycin_dose': {
        'unit':     'mg',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Vancomycin',
    },
    'vasopressin_dose': {
        'unit':     '',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Vasopressin',
    },
    'vasopressors_dose': {
        'unit':     '',
        'value':    float,
        'thresh':   (None, None),
        'human_readable':   'Vasopressors',
    },
    'vent': {
        'unit':     '',
        'value':    str,
        'thresh':   (None, None),
        'human_readable':   'Mechanical Ventilation',
    },
    'wbc': {
        'unit':     '1000/uL',
        'value':    float,
        'thresh':   (0.1, 70),
        'human_readable':   'WBC',
    },
    'weight': {
        'unit':     'kg',
        'value':    float,
        'thresh':   (0.1, 300),
        'human_readable':   'Weight',
    },
}
