---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx-config: |-
    server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
        server_name _;
        location / {
          proxy_pass http://127.0.0.1:8000;
        }
    }
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: trews-rest-api-test
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: trews-rest-api-test
    spec:
      nodeSelector:
        opsdx_nodegroup: spot-nodes
      containers:
      - name: trews-nginx
        image: nginx:alpine
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
        volumeMounts:
          - name: config-volume
            mountPath: "/etc/nginx/conf.d/"
      - name: trews-rest-api-test
        image: 359300513585.dkr.ecr.us-east-1.amazonaws.com/universe:latest
        resources:
          requests:
            memory: "2816Mi"
            cpu: "1000m"
        ports:
        - containerPort: 8000
        command: ["/bin/sh","-c"]
        args: ["cd api;sh start-dev.sh"]
        securityContext:
          capabilities:
            add:
            - "SYS_PTRACE"
        env:
        #- name: force_pat_ids
        #  value: "comma_separated_pat_ids"
        #
        #- name: user_whitelist
        #  value: "comma_separated_user_ids"
        #
        #- name: disabled_msg
        #  value: "TREWS: coming soon"
        #
        #- name: no_check_for_orders
        #  value: "True"
        #
        - name: epic_server
          value: "test"
        - name: release
          value: "epic2017"
        - name: model_in_use
          value: "trews-jit"
        - name: v1_flowsheets
          value: "true"
        - name: soi_flowsheet
          value: "true"
        - name: db_host
          value: "dev.db.jh.opsdx.io"
        - name: db_port
          value: "5432"
        - name: db_name
          value: "opsdx_test"
        - name: db_user
          valueFrom:
            secretKeyRef:
              name: rest-api-db-secrets
              key: db-username
        - name: db_password
          valueFrom:
            secretKeyRef:
              name: rest-api-db-secrets
              key: db-password
        - name: jhapi_client_id
          valueFrom:
            secretKeyRef:
              name: rest-api-db-secrets
              key: jhapi-client-id
        - name: jhapi_client_secret
          valueFrom:
            secretKeyRef:
              name: rest-api-db-secrets
              key: jhapi-client-secret
        - name: AWS_DEFAULT_REGION
          valueFrom:
            secretKeyRef:
              name: rest-api-db-secrets
              key: aws-region
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: rest-api-db-secrets
              key: aws-access-key-id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: rest-api-db-secrets
              key: aws-secret-access-key
        - name: querystring_key
          valueFrom:
            secretKeyRef:
              name: rest-api-db-secrets
              key: querystring-key
        - name: trews_app_key
          valueFrom:
            secretKeyRef:
              name: rest-api-db-secrets
              key: trews-app-key
        - name: trews_admin_key
          valueFrom:
            secretKeyRef:
              name: rest-api-db-secrets
              key: trews-admin-key
        - name: ie_mode
          value: "edge"
        - name: order_link_mode
          value: "direct"
        - name: order_signing_timeout_secs
          value: "30"
        - name: order_poll_rate_secs
          value: "5"
        - name: log_decryption
          value: "true"
        - name: log_user_latency
          value: "false"
        - name: trews_open_access
          value: "false"
        - name: epic_notifications
          value: "1"
        - name: logging
          value: "1"
        - name: logging_period
          value: "20"
        - name: cloudwatch_log_group
          value: "opsdx-web-logs-test"
        - name: api_with_healthcheck
          value: "1"
        - name: api_monitor
          value: "1"
        - name: api_monitor_prometheus
          value: "0"
        - name: api_monitor_cw_push_period
          value: "10"
        - name: prometheus_multiproc_dir
          value: "/tmp"
        - name: etl_channel
          value: "on_opsdx_dev_etl"
        - name: chart_sample_start_hrs
          value: "6"
        - name: chart_sample_start_day
          value: "2"
        - name: chart_sample_end_day
          value: "7"
        - name: chart_sample_mins
          value: "30"
        - name: chart_sample_hrs
          value: "4"
      volumes:
        - name: config-volume
          configMap:
            name: nginx-config
            items:
              - key: nginx-config
                path: trews.conf
---
apiVersion: v1
kind: Service
metadata:
  name: trews-rest-svc-test
  labels:
    app: trews-rest-api-test
spec:
  type: NodePort
  ports:
  - port: 80
    name: http
    targetPort: 80
  selector:
    app: trews-rest-api-test
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: trews-rest-ingress-test
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/affinity: "cookie"
    ingress.kubernetes.io/session-cookie-name: "route"
    ingress.kubernetes.io/session-cookie-hash: "sha1"
    ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
  - host: trews-dev.jh.opsdx.io
    http:
      paths:
      - backend:
          serviceName: trews-rest-svc-test
          servicePort: 80
        path: /
